In [5]:
import pandas as pd
import numpy as np

In [7]:
np.random.seed(42)

In [13]:
n=70
age = np.random.randint(15,65,n)
salary = np.random.normal(10000, 70000, n)
salary[np.random.choice(n, 10, replace=False)] = np.nan

In [7]:
#PROBLEM 1
#(a)

In [23]:
df = pd.DataFrame({'age': age, 'salary': salary})
df

age         salary
0    55   67544.211200
1    47            NaN
2    54   -7177.168120
3    53  -42761.531505
4    32  -52266.010074
..  ...            ...
65   62   25152.101271
66   34   13190.028793
67   22            NaN
68   21  160076.086253
69   17   54374.331562

[70 rows x 2 columns]

In [25]:
df['salary'].mean()

19738.10556597439

In [27]:
#(b) 
df['salary'].median()

18245.973586614768

In [29]:
(df['salary']*df['age']).sum()/df['age'].sum()

20693.433873019127

In [27]:
#PROBLEM 2

In [33]:
#z-score
z_score = (df['salary']-df['salary'].mean(skipna=True)/df['salary'].std(skipna=True))

In [35]:
z_score

0      67543.943491
1               NaN
2      -7177.435829
3     -42761.799214
4     -52266.277783
          ...      
65     25151.833562
66     13189.761084
67              NaN
68    160075.818544
69     54374.063853
Name: salary, Length: 70, dtype: float64

In [37]:
outlier = (abs(z_score) > 3).sum()
outlier

60

In [45]:
#PROBLEM 3

In [43]:
labels = ["18-25", "25-35", "35-45", "45-60"]
bins = [18, 25, 35, 45, 60]

df['age_bin'] = pd.cut(df['age'], bins=bins, labels=labels, right=False)


res = df.groupby('age_bin', observed=False).agg(
    count=('salary', 'count'),
    mean_income=('salary', 'mean'),
    median_income=('salary', 'median')
).reset_index().sort_values('age_bin')

print(res)




  age_bin  count   mean_income  median_income
0   18-25      6  27951.178985   34043.840687
1   25-35     12   6354.162522   -4033.008926
2   35-45     11  27208.651628   -5642.394973
3   45-60     19  26735.627582   36972.216581


In [63]:
#PROBLEM 4

In [47]:
arr = np.random.randint(1, 10, (3, 4))
arr

array([[5, 4, 8, 7],
       [2, 1, 4, 8],
       [2, 3, 1, 1]])

In [51]:
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Transposed:", arr.T)
print("Flattened:", arr.flatten())

Shape: (3, 4)
Size: 12
Transposed: [[5 2 2]
 [4 1 3]
 [8 4 1]
 [7 8 1]]
Flattened: [5 4 8 7 2 1 4 8 2 3 1 1]


In [53]:
print("Last row:", arr[-1])

try:
    slice_error = arr[:, 10]
except Exception as e:
    print("Slicing error:", e)

Last row: [2 3 1 1]
Slicing error: index 10 is out of bounds for axis 1 with size 4


In [55]:
arr2 = np.random.randint(1, 10, (3, 1))
broadcasted = arr + arr2 
print("Broadcasted:\n", broadcasted)
dot_product = np.dot(arr, arr.T)
print("Dot Product:\n", dot_product)

Broadcasted:
 [[ 8  7 11 10]
 [ 7  6  9 13]
 [ 5  6  4  4]]
Dot Product:
 [[154 102  37]
 [102  85  19]
 [ 37  19  15]]


In [57]:
square_arr = np.random.randint(1, 10, (3, 3))
det = np.linalg.det(square_arr)
inverse = np.linalg.inv(square_arr)

print("Square Array:\n", square_arr)
print("Determinant:", det)
print("Inverse:\n", inverse)

Square Array:
 [[1 1 8]
 [2 3 2]
 [3 7 1]]
Determinant: 33.000000000000014
Inverse:
 [[-0.33333333  1.66666667 -0.66666667]
 [ 0.12121212 -0.6969697   0.42424242]
 [ 0.15151515 -0.12121212  0.03030303]]
